from gym.envs.classic_control.cartpole import CartPoleEnv
from gym.envs.classic_control.mountain_car import MountainCarEnv
from gym.envs.classic_control.continuous_mountain_car import Continuous_MountainCarEnv
from gym.envs.classic_control.pendulum import PendulumEnv
from gym.envs.classic_control.acrobot import AcrobotEnv
from gym.envs.classic_control.simpleVShape import SimpleVShape
from gym.envs.classic_control.simpleVShape2 import SimpleVShape2
from gym.envs.classic_control.cat2D import cat2D
from gym.envs.classic_control.cat3D import cat3D